### PR TITLE
Initialize CI

### PR DESCRIPTION
**Pull request by archaeron**
the
- nix/sources.json
- nix/sources.nix
are auto generated by [niv](https://github.com/nmattia/niv)

I have included all the necessary code to install idris2.

and it would be great if you could add the key to the cachix store I've created, so that the CI keeps fast enough

What do you think of this approach?

### CODE REVIEW

**Comment by meraymond2** [comment]
It looks good :+1: 

How do I get the key to put it into the secrets?

**Comment by archaeron** [comment]
@meraymond2 do you have a twitter or something where I can send you a direct message for the key? Alternatively you could open your own cache on cachix and add the key in the github settings under secrets as `CACHIX_SIGNING_KEY`.

**Comment by archaeron** [comment]
for the Idris 2 test we need to think about what we want. I assume the tests would fail right now?
I could add the tests and make even the failing tests "pass" so that we can see the output?

**Comment by meraymond2** [comment]
I don't have a twitter, can you just email it to me at michael_raymond@fastmail.com? We can use the one you've already created.

I'm not entirely sure what the Idris2 tests should do. At the moment (on the other branch), they'll fail, but it should be possible to use passing tests instead, where the expected value is the unimplemented reply. I went back and forth a bit, but I think it makes more sense to do the latter, after all, we're testing that the client has understood the IDE, not that the IDE is completely implemented. 

I think either way, it'll be easier to keep them as separate test files.

**Comment by archaeron** [comment]
I have sent the key to your mail address.

Do you have a second test for the idris2 tests? I can try to put that into the CI in a separate PR.

**Comment by meraymond2** [comment]
Added the key :+1:

The new tests are on the https://github.com/meraymond2/idris-ide-client/pull/13 branch. I'm going to merge this in, and we can update the CI when those tests are merged.

**Pull request merged**
